// <auto-generated />
using System;
using AspnetCoreStudy.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspnetCoreStudy.Migrations
{
    [DbContext(typeof(AspnetCoreStudyDbContext))]
    [Migration("20190911132914_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspnetCoreStudy.Models.Member", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserEmail")
                        .IsRequired();

                    b.Property<string>("UserGender")
                        .IsRequired();

                    b.Property<string>("UserNm")
                        .IsRequired();

                    b.Property<string>("UserPhoto");

                    b.Property<string>("UserPw")
                        .IsRequired();

                    b.Property<DateTime>("UserReg");

                    b.HasKey("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("AspnetCoreStudy.Models.Post", b =>
                {
                    b.Property<int>("PostNum")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PostContent")
                        .IsRequired();

                    b.Property<int>("PostGroup");

                    b.Property<DateTime>("PostReg");

                    b.Property<string>("PostTittle")
                        .IsRequired();

                    b.Property<int>("PostViews");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("PostNum");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("AspnetCoreStudy.Models.Reply", b =>
                {
                    b.Property<int>("ReplyNum")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReplyContent")
                        .IsRequired();

                    b.Property<DateTime>("ReplyReg");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("ReplyNum");

                    b.HasIndex("UserId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("AspnetCoreStudy.Models.Post", b =>
                {
                    b.HasOne("AspnetCoreStudy.Models.Member", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AspnetCoreStudy.Models.Reply", b =>
                {
                    b.HasOne("AspnetCoreStudy.Models.Member", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
